- name: Build and Deploy Docker Container
  hosts: localhost

  tasks:
    - name: Building Docker image
      docker_image:
        name: my_img
        source: build
        build:
          path: .
        state: present

    - name: Stopping existing Container
      docker_container:
        name: my_container
        image: my_img
        state: stopped

    - name: Removing stopped Container
      docker_container:
        name: my_container
        image: my_img
        state: absent

    - name: Creating the Container
      docker_container:
        name: my_container
        image: my_img
        ports:
          - "8093:80"
        state: started